services:
  - type: web
    name: mpd-proxy
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: ORIGIN
        value: "http://143.44.136.67:6060/001/2/ch00000090990000001143"
